### ISSUE TITLE
Some issues fix for DDR4 Rams

### ISSUE THREAD

**Issue by aarmn** [icy/ram_free5G#1]
At least make it a swap partition or sth so it show up as extra ram (also to make the pain more, make it 5gb of bit 0)
Also readme.md download link needs to be main not master (anyways it's empty so doesn't matter much)

**Comment by icy** [comment]
> At least make it a swap partition or sth so it show up as extra ram (also to make the pain more, make it 5gb of bit 0) 

Would you mind giving a pull request? Thanks a lot.

> Also readme.md download link needs to be main not master (anyways it's empty so doesn't matter much)

You're right. Now it's called "main", but the link is still good. I will fix to match with default branch.

**Comment by aarmn** [comment]
Hmm, I'll give it a try, won't promise!

**Comment by icy** [comment]
> Hmm, I'll give it a try, won't promise!

Thanks in advance. I was to add a swap partition info, but then I pushed the code when one of my colleagues complained that his Linux laptop was running out of memory ;) We definitely add more pain sooner or later ;)

**Comment by aarmn** [comment]
Sure😆, I was working on it and found swapon command, that single-handedly (probably) make it a piece of cake to write a bash script to do the wanted functionality
also, I found out swapfiles (as I got them) can be literally anything, even a bunch of literal zero bytes because that's what actually ram is (no real file-system).
rn I'm on a windows machine if you can give it a try and check (with lsblk or sth, I dunno really) would it be added as ram or not (again, as far as I got, you can literally make a 1GB of zero and give it as it and it would serve the purpose)

check this tutorial, its super easy, just a sh file, and for sure to make it lovely don't let users get their hand dirty on creating that file and make them download those zeros 😆: https://linuxize.com/post/create-a-linux-swap-file/

also if you have hands-on a Linux system, check that would it add that swap file on top of the normal swap or it would ignore the old (probably drive of) swap?

**Comment by icy** [comment]
@aarmn Thanks for your sharing and for the nice idea. 

Making the swapfile available on Github is cool, though it can be a big file (the size is fixed), not sure if it can be compressed. I'm using Linux and I would give a try soon.

Having a script is also a nice option, of course, with more liability ;)
